[package]
name = "web-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
chrono="0.2"
[dependencies.async-std]
version = "1.6"
features = ["attributes"]